CREATE TABLE im_apps(
    id INT(11) PRIMARY KEY AUTO_INCREMENT,
    app_key VARCHAR(20),
    app_secret VARCHAR(20),
    app_secure_key VARCHAR(20),
    app_status VARCHAR(10),
    created_time TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)
ENGINE=InnoDB
DEFAULT CHARACTER SET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE im_appexts(
    id INT(11) PRIMARY KEY AUTO_INCREMENT,
    app_key VARCHAR(20),
    app_item_key VARCHAR(20),
    app_item_value VARCHAR(512),
    created_time TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)
ENGINE=InnoDB
DEFAULT CHARACTER SET=utf8 COLLATE=utf8_general_ci;